name: Deploy Production

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Slack Start
        uses: slackapi/slack-github-action@v2
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: |
              🚀 Production gestartet

              Benutzer:
              ${{ github.actor }}

              Workflow:
              ${{ github.workflow }}

      - uses: actions/checkout@v4

      - name: SSH vorbereiten
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy Production
        run: |
          for SERVER in ${{ secrets.EC2_IPS_PROD }}
          do
            ssh-keyscan -H $SERVER >> ~/.ssh/known_hosts
            scp -i ~/.ssh/id_rsa Frontend/index.html ubuntu@$SERVER:/tmp/index.html
            ssh -i ~/.ssh/id_rsa ubuntu@$SERVER "sudo cp /tmp/index.html /var/www/html/index.html"
          done

      - name: Slack Erfolg
        if: success()
        uses: slackapi/slack-github-action@v2
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: |
              ✅ Production erfolgreich

      - name: Slack Fehler
        if: failure()
        uses: slackapi/slack-github-action@v2
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: |
              ❌ Production fehlgeschlagen