name: Deploy to Production

on:
  push:
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Production EC2s
        run: |
          IFS=' ' read -ra IPS <<< "${{ secrets.EC2_IPS_PROD }}"
          for IP in "${IPS[@]}"; do
            scp -o StrictHostKeyChecking=no -i /home/ubuntu/.ssh/id_rsa index.html ubuntu@$IP:/var/www/html/index.html
            ssh -o StrictHostKeyChecking=no -i /home/ubuntu/.ssh/id_rsa ubuntu@$IP "sudo systemctl restart nginx"
          done
